#!/bin/bash

if [ "$1" == 0 ]; then
Zero=0
shift 
elif [ "$1" == 1 ]; then
Zero=1
shift
elif [ "$1" == 2 ]; then
Zero=2
shift
else
Zero=1
fi

rm conf.txt

while [ -n "$1" ]; do

file=conf.txt
if [ "$Zero" == 1 ] ; then
echo "$1" $(grep -a'nic and z' $1 | tail -1 | awk '{print $7}') $(grep -a 'Dipole moment' -A1 $1 | tail -1 | awk '{print $8}' ) >> $file
elif [ "$Zero" == 2 ] ; then
echo "$1" $(grep -a 'al Free' $1 | tail -1 | awk '{print $8}') $(grep -a 'Dipole moment' -A1 $1 | tail -1 | awk '{print $8}' ) >> $file
else
echo "$1" $(grep -a E\( $1 | tail -1 | awk '{print $5}') $(grep -a 'Dipole moment' -A1 $1 | tail -1 | awk '{print $8}' ) >> $file
fi

shift

done

if [ "$Zero" == 1 ]; then
python ~/bin/elim.py 1
else
python ~/bin/elim.py 0
fi


del=$(wc myfile | awk '{ print $1 }')
if [ $del == 1 ]; then
rm $file
fi
rm myfile
